-- D&D 2024 Spells Database SQL Insert Statements

INSERT INTO spells (id, name, level, school, casting_time, range, area, components, duration, concentration, ritual, classes, description, higher_levels, img_url, created_at, updated_at) VALUES
(1, 'Acid Splash', '0', 'Evocation', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, 'You hurl a bubble of acid. Choose one or two creatures you can see within range. If you choose two, they must be within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.', NULL, NULL, NULL, NULL),
(2, 'Aid', '2', 'Abjuration', 'Action', '30 ft', NULL, 'V,S,M', '8 hours', 0, 0, NULL, 'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target''s hit point maximum and current hit points increase by 5 for the duration.', NULL, NULL, NULL, NULL),
(3, 'Alarm', '1', 'Abjuration', '1 minute or Ritual', '30 ft', NULL, 'V,S,M', '8 hours', 0, 1, NULL, 'You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area.', NULL, NULL, NULL, NULL),
(4, 'Alter Self', '2', 'Transmutation', 'Action', 'Self', NULL, 'V,S', '1 hour', 1, 0, NULL, 'You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell.', NULL, NULL, NULL, NULL),
(5, 'Animal Friendship', '1', 'Enchantment', 'Action', '30 ft', NULL, 'V,S,M', '24 hours', 0, 0, NULL, 'This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast''s Intelligence is 4 or higher, the spell fails.', NULL, NULL, NULL, NULL),
(6, 'Animal Messenger', '2', 'Enchantment', 'Action or Ritual', '30 ft', NULL, 'V,S,M', '24 hours', 0, 1, NULL, 'By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat.', NULL, NULL, NULL, NULL),
(7, 'Animal Shapes', '8', 'Transmutation', 'Action', '30 ft', NULL, 'V,S', '24 hours', 0, 0, NULL, 'Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower.', NULL, NULL, NULL, NULL),
(8, 'Animate Dead', '3', 'Necromancy', '1 minute', '10 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, 'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature.', NULL, NULL, NULL, NULL),
(9, 'Animate Objects', '5', 'Transmutation', 'Action', '120 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, 'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects.', NULL, NULL, NULL, NULL),
(10, 'Antilife Shell', '5', 'Abjuration', 'Action', 'Self', NULL, 'V,S', '1 hour', 1, 0, NULL, 'A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs.', NULL, NULL, NULL, NULL),
(11, 'Antimagic Field', '8', 'Abjuration', 'Action', 'Self', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/antimagic-field', NULL, NULL),
(12, 'Antipathy/Sympathy', '8', 'Enchantment', '1 hour', '60 ft', NULL, 'V,S,M', '10 days', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/antipathy/sympathy', NULL, NULL),
(13, 'Arcane Eye', '4', 'Divination', 'Action', '30 ft', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/arcane-eye', NULL, NULL),
(14, 'Arcane Gate', '6', 'Conjuration', 'Action', '500 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/arcane-gate', NULL, NULL),
(15, 'Arcane Lock', '2', 'Abjuration', 'Action', 'Touch', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/arcane-lock', NULL, NULL),
(16, 'Arcane Vigor', '2', 'Abjuration', 'Bonus Action', 'Self', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/arcane-vigor', NULL, NULL),
(17, 'Armor of Agathys', '1', 'Abjuration', 'Bonus Action', 'Self', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/armor-of-agathys', NULL, NULL),
(18, 'Arms of Hadar', '1', 'Conjuration', 'Action', 'Self', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/arms-of-hadar', NULL, NULL),
(19, 'Astral Projection', '9', 'Necromancy', '1 hour', '10 ft', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/astral-projection', NULL, NULL),
(20, 'Augury', '2', 'Divination', '1 minute or Ritual', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/augury', NULL, NULL),
(21, 'Aura of Life', '4', 'Abjuration', 'Action', 'Self', NULL, 'V', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/aura-of-life', NULL, NULL),
(22, 'Aura of Purity', '4', 'Abjuration', 'Action', 'Self', NULL, 'V', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/aura-of-purity', NULL, NULL),
(23, 'Aura of Vitality', '3', 'Abjuration', 'Action', 'Self', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/aura-of-vitality', NULL, NULL),
(24, 'Awaken', '5', 'Transmutation', '8 hours', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/awaken', NULL, NULL),
(25, 'Bane', '1', 'Enchantment', 'Action', '30 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/bane', NULL, NULL),
(26, 'Banishing Smite', '5', 'Conjuration', 'Bonus Action', 'Self', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/banishing-smite', NULL, NULL),
(27, 'Banishment', '4', 'Abjuration', 'Action', '30 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/banishment', NULL, NULL),
(28, 'Barkskin', '2', 'Transmutation', 'Bonus Action', 'Touch', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/barkskin', NULL, NULL),
(29, 'Beacon of Hope', '3', 'Abjuration', 'Action', '30 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/beacon-of-hope', NULL, NULL),
(30, 'Beast Sense', '2', 'Divination', 'Action or Ritual', 'Touch', NULL, 'S', '1 hour', 1, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/beast-sense', NULL, NULL),
(31, 'Befuddlement', '8', 'Enchantment', 'Action', '150 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/befuddlement', NULL, NULL),
(32, 'Bestow Curse', '3', 'Necromancy', 'Action', 'Touch', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/bestow-curse', NULL, NULL),
(33, 'Bigby''s Hand', '5', 'Evocation', 'Action', '120 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/bigby-s-hand', NULL, NULL),
(34, 'Blade Barrier', '6', 'Evocation', 'Action', '90 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blade-barrier', NULL, NULL),
(35, 'Blade Ward', '0', 'Abjuration', 'Action', 'Self', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blade-ward', NULL, NULL),
(36, 'Bless', '1', 'Enchantment', 'Action', '30 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/bless', NULL, NULL),
(37, 'Blight', '4', 'Necromancy', 'Action', '30 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blight', NULL, NULL),
(38, 'Blinding Smite', '3', 'Evocation', 'Bonus Action', 'Self', NULL, 'V', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blinding-smite', NULL, NULL),
(39, 'Blindness/Deafness', '2', 'Transmutation', 'Action', '120 ft', NULL, 'V', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blindness/deafness', NULL, NULL),
(40, 'Blink', '3', 'Transmutation', 'Action', 'Self', NULL, 'V,S', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blink', NULL, NULL),
(41, 'Blur', '2', 'Illusion', 'Action', 'Self', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/blur', NULL, NULL),
(42, 'Burning Hands', '1', 'Evocation', 'Action', 'Self', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/burning-hands', NULL, NULL),
(43, 'Call Lightning', '3', 'Conjuration', 'Action', '120 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/call-lightning', NULL, NULL),
(44, 'Calm Emotions', '2', 'Enchantment', 'Action', '60 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/calm-emotions', NULL, NULL),
(45, 'Chain Lightning', '6', 'Evocation', 'Action', '150 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/chain-lightning', NULL, NULL),
(46, 'Charm Monster', '4', 'Enchantment', 'Action', '30 ft', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/charm-monster', NULL, NULL),
(47, 'Charm Person', '1', 'Enchantment', 'Action', '30 ft', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/charm-person', NULL, NULL),
(48, 'Chill Touch', '0', 'Necromancy', 'Action', 'Touch', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/chill-touch', NULL, NULL),
(49, 'Chromatic Orb', '1', 'Evocation', 'Action', '90 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/chromatic-orb', NULL, NULL),
(50, 'Circle of Death', '6', 'Necromancy', 'Action', '150 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/circle-of-death', NULL, NULL),
(51, 'Circle of Power', '5', 'Abjuration', 'Action', 'Self', NULL, 'V', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/circle-of-power', NULL, NULL),
(52, 'Clairvoyance', '3', 'Divination', '10 minutes', '1 mile', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/clairvoyance', NULL, NULL),
(53, 'Clone', '8', 'Necromancy', '1 hour', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/clone', NULL, NULL),
(54, 'Cloud of Daggers', '2', 'Conjuration', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/cloud-of-daggers', NULL, NULL),
(55, 'Cloudkill', '5', 'Conjuration', 'Action', '120 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/cloudkill', NULL, NULL),
(56, 'Color Spray', '1', 'Illusion', 'Action', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/color-spray', NULL, NULL),
(57, 'Command', '1', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/command', NULL, NULL),
(58, 'Commune', '5', 'Divination', '1 minute or Ritual', 'Self', NULL, 'V,S,M', '1 minute', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/commune', NULL, NULL),
(59, 'Commune with Nature', '5', 'Divination', '1 minute or Ritual', 'Self', NULL, 'V,S', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/commune-with-nature', NULL, NULL),
(60, 'Compelled Duel', '1', 'Enchantment', 'Bonus Action', '30 ft', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/compelled-duel', NULL, NULL),
(61, 'Comprehend Languages', '1', 'Divination', 'Action or Ritual', 'Self', NULL, 'V,S,M', '1 hour', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/comprehend-languages', NULL, NULL),
(62, 'Compulsion', '4', 'Enchantment', 'Action', '30 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/compulsion', NULL, NULL),
(63, 'Cone of Cold', '5', 'Evocation', 'Action', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/cone-of-cold', NULL, NULL),
(64, 'Confusion', '4', 'Enchantment', 'Action', '90 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/confusion', NULL, NULL),
(65, 'Conjure Animals', '3', 'Conjuration', 'Action', '60 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-animals', NULL, NULL),
(66, 'Conjure Barrage', '3', 'Conjuration', 'Action', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-barrage', NULL, NULL),
(67, 'Conjure Celestial', '7', 'Conjuration', 'Action', '90 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-celestial', NULL, NULL),
(68, 'Conjure Elemental', '5', 'Conjuration', 'Action', '60 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-elemental', NULL, NULL),
(69, 'Conjure Fey', '6', 'Conjuration', 'Action', '60 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-fey', NULL, NULL),
(70, 'Conjure Minor Elementals', '4', 'Conjuration', 'Action', 'Self', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-minor-elementals', NULL, NULL),
(71, 'Conjure Volley', '5', 'Conjuration', 'Action', '150 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-volley', NULL, NULL),
(72, 'Conjure Woodland Beings', '4', 'Conjuration', 'Action', 'Self', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/conjure-woodland-beings', NULL, NULL),
(73, 'Contact Other Plane', '5', 'Divination', '1 minute or Ritual', 'Self', NULL, 'V', '1 minute', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/contact-other-plane', NULL, NULL),
(74, 'Contagion', '5', 'Necromancy', 'Action', 'Touch', NULL, 'V,S', '7 days', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/contagion', NULL, NULL),
(75, 'Contingency', '6', 'Abjuration', '10 minutes', 'Self', NULL, 'V,S,M', '10 days', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/contingency', NULL, NULL),
(76, 'Continual Flame', '2', 'Evocation', 'Action', 'Touch', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/continual-flame', NULL, NULL),
(77, 'Control Water', '4', 'Transmutation', 'Action', '300 ft', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/control-water', NULL, NULL),
(78, 'Control Weather', '8', 'Transmutation', '10 minutes', 'Self', NULL, 'V,S,M', '8 hours', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/control-weather', NULL, NULL),
(79, 'Cordon of Arrows', '2', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/cordon-of-arrows', NULL, NULL),
(80, 'Counterspell', '3', 'Abjuration', 'Reaction', '60 ft', NULL, 'S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/counterspell', NULL, NULL),
(81, 'Create Food and Water', '3', 'Conjuration', 'Action', '30 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/create-food-and-water', NULL, NULL),
(82, 'Create or Destroy Water', '1', 'Transmutation', 'Action', '30 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/create-or-destroy-water', NULL, NULL),
(83, 'Create Undead', '6', 'Necromancy', '1 minute', '10 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/create-undead', NULL, NULL),
(84, 'Creation', '5', 'Illusion', '1 minute', '30 ft', NULL, 'V,S,M', 'Special', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/creation', NULL, NULL),
(85, 'Crown of Madness', '2', 'Enchantment', 'Action', '120 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/crown-of-madness', NULL, NULL),
(86, 'Crusader''s Mantle', '3', 'Evocation', 'Action', 'Self', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/crusader-s-mantle', NULL, NULL),
(87, 'Cure Wounds', '1', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/cure-wounds', NULL, NULL),
(88, 'Dancing Lights', '0', 'Illusion', 'Action', '120 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dancing-lights', NULL, NULL),
(89, 'Darkness', '2', 'Evocation', 'Action', '60 ft', NULL, 'V,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/darkness', NULL, NULL),
(90, 'Darkvision', '2', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/darkvision', NULL, NULL),
(91, 'Daylight', '3', 'Evocation', 'Action', '60 ft', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/daylight', NULL, NULL),
(92, 'Death Ward', '4', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/death-ward', NULL, NULL),
(93, 'Delayed Blast Fireball', '7', 'Evocation', 'Action', '150 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/delayed-blast-fireball', NULL, NULL),
(94, 'Demiplane', '8', 'Conjuration', 'Action', '60 ft', NULL, 'S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/demiplane', NULL, NULL),
(95, 'Destructive Wave', '5', 'Evocation', 'Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/destructive-wave', NULL, NULL),
(96, 'Detect Evil and Good', '1', 'Divination', 'Action', 'Self', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/detect-evil-and-good', NULL, NULL),
(97, 'Detect Magic', '1', 'Divination', 'Action or Ritual', 'Self', NULL, 'V,S', '10 minutes', 1, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/detect-magic', NULL, NULL),
(98, 'Detect Poison and Disease', '1', 'Divination', 'Action or Ritual', 'Self', NULL, 'V,S,M', '10 minutes', 1, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/detect-poison-and-disease', NULL, NULL),
(99, 'Detect Thoughts', '2', 'Divination', 'Action', 'Self', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/detect-thoughts', NULL, NULL),
(100, 'Dimension Door', '4', 'Conjuration', 'Action', '500 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dimension-door', NULL, NULL),
(101, 'Disguise Self', '1', 'Illusion', 'Action', 'Self', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/disguise-self', NULL, NULL),
(102, 'Disintegrate', '6', 'Transmutation', 'Action', '60 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/disintegrate', NULL, NULL),
(103, 'Dispel Evil and Good', '5', 'Abjuration', 'Action', 'Self', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dispel-evil-and-good', NULL, NULL),
(104, 'Dispel Magic', '3', 'Abjuration', 'Action', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dispel-magic', NULL, NULL),
(105, 'Dissonant Whispers', '1', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dissonant-whispers', NULL, NULL),
(106, 'Divination', '4', 'Divination', 'Action or Ritual', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/divination', NULL, NULL),
(107, 'Divine Favor', '1', 'Transmutation', 'Bonus Action', 'Self', NULL, 'V,S', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/divine-favor', NULL, NULL),
(108, 'Divine Smite', '1', 'Evocation', 'Bonus Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/divine-smite', NULL, NULL),
(109, 'Divine Word', '7', 'Evocation', 'Bonus Action', '30 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/divine-word', NULL, NULL),
(110, 'Dominate Beast', '4', 'Enchantment', 'Action', '60 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dominate-beast', NULL, NULL),
(111, 'Dominate Monster', '8', 'Enchantment', 'Action', '60 ft', NULL, 'V,S', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dominate-monster', NULL, NULL),
(112, 'Dominate Person', '5', 'Enchantment', 'Action', '60 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dominate-person', NULL, NULL),
(113, 'Dragon''s Breath', '2', 'Transmutation', 'Bonus Action', 'Touch', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dragon-s-breath', NULL, NULL),
(114, 'Drawmij''s Instant Summons', '6', 'Conjuration', '1 minute or Ritual', 'Touch', NULL, 'V,S,M', 'Dispelled', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/drawmij-s-instant-summons', NULL, NULL),
(115, 'Dream', '5', 'Illusion', '1 minute', 'Special', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/dream', NULL, NULL),
(116, 'Druidcraft', '0', 'Transmutation', 'Action', '30 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/druidcraft', NULL, NULL),
(117, 'Earthquake', '8', 'Transmutation', 'Action', '500 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/earthquake', NULL, NULL),
(118, 'Eldritch Blast', '0', 'Evocation', 'Action', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/eldritch-blast', NULL, NULL),
(119, 'Elemental Weapon', '3', 'Transmutation', 'Action', 'Touch', NULL, 'V,S', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/elemental-weapon', NULL, NULL),
(120, 'Elementalism', '0', 'Transmutation', 'Action', '30 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/elementalism', NULL, NULL),
(121, 'Enhance Ability', '2', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/enhance-ability', NULL, NULL),
(122, 'Enlarge/Reduce', '2', 'Transmutation', 'Action', '30 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/enlarge/reduce', NULL, NULL),
(123, 'Ensnaring Strike', '1', 'Conjuration', 'Bonus Action', 'Self', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/ensnaring-strike', NULL, NULL),
(124, 'Entangle', '1', 'Conjuration', 'Action', '90 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/entangle', NULL, NULL),
(125, 'Enthrall', '2', 'Enchantment', 'Action', '60 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/enthrall', NULL, NULL),
(126, 'Etherealness', '7', 'Conjuration', 'Action', 'Self', NULL, 'V,S', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/etherealness', NULL, NULL),
(127, 'Evard''s Black Tentacles', '4', 'Conjuration', 'Action', '90 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/evard-s-black-tentacles', NULL, NULL),
(128, 'Expeditious Retreat', '1', 'Transmutation', 'Bonus Action', 'Self', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/expeditious-retreat', NULL, NULL),
(129, 'Eyebite', '6', 'Necromancy', 'Action', 'Self', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/eyebite', NULL, NULL),
(130, 'Fabricate', '4', 'Transmutation', '10 minutes', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fabricate', NULL, NULL),
(131, 'Faerie Fire', '1', 'Evocation', 'Action', '60 ft', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/faerie-fire', NULL, NULL),
(132, 'False Life', '1', 'Necromancy', 'Action', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/false-life', NULL, NULL),
(133, 'Fear', '3', 'Illusion', 'Action', 'Self', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fear', NULL, NULL),
(134, 'Feather Fall', '1', 'Transmutation', 'Reaction', '60 ft', NULL, 'V,M', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/feather-fall', NULL, NULL),
(135, 'Feign Death', '3', 'Necromancy', 'Action or Ritual', 'Touch', NULL, 'V,S,M', '1 hour', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/feign-death', NULL, NULL),
(136, 'Find Familiar', '1', 'Conjuration', '1 hour or Ritual', '10 ft', NULL, 'V,S,M', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/find-familiar', NULL, NULL),
(137, 'Find Steed', '2', 'Conjuration', 'Action', '30 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/find-steed', NULL, NULL),
(138, 'Find the Path', '6', 'Divination', '1 minute', 'Self', NULL, 'V,S,M', '1 day', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/find-the-path', NULL, NULL),
(139, 'Find Traps', '2', 'Divination', 'Action', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/find-traps', NULL, NULL),
(140, 'Finger of Death', '7', 'Necromancy', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/finger-of-death', NULL, NULL),
(141, 'Fire Bolt', '0', 'Evocation', 'Action', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fire-bolt', NULL, NULL),
(142, 'Fire Shield', '4', 'Evocation', 'Action', 'Self', NULL, 'V,S,M', '10 minutes', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fire-shield', NULL, NULL),
(143, 'Fire Storm', '7', 'Evocation', 'Action', '150 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fire-storm', NULL, NULL),
(144, 'Fireball', '3', 'Evocation', 'Action', '150 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fireball', NULL, NULL),
(145, 'Flame Blade', '2', 'Evocation', 'Bonus Action', 'Self', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/flame-blade', NULL, NULL),
(146, 'Flame Strike', '5', 'Evocation', 'Action', '60 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/flame-strike', NULL, NULL),
(147, 'Flaming Sphere', '2', 'Conjuration', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/flaming-sphere', NULL, NULL),
(148, 'Flesh to Stone', '6', 'Transmutation', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/flesh-to-stone', NULL, NULL),
(149, 'Fly', '3', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fly', NULL, NULL),
(150, 'Fog Cloud', '1', 'Conjuration', 'Action', '120 ft', NULL, 'V,S', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fog-cloud', NULL, NULL),
(151, 'Forbiddance', '6', 'Abjuration', '10 minutes or Ritual', 'Touch', NULL, 'V,S,M', '1 day', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/forbiddance', NULL, NULL),
(152, 'Forcecage', '7', 'Evocation', 'Action', '100 ft', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/forcecage', NULL, NULL),
(153, 'Foresight', '9', 'Divination', '1 minute', 'Touch', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/foresight', NULL, NULL),
(154, 'Fount of Moonlight', '4', 'Evocation', 'Action', 'Self', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/fount-of-moonlight', NULL, NULL),
(155, 'Freedom of Movement', '4', 'Abjuration', 'Action', 'Touch', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/freedom-of-movement', NULL, NULL),
(156, 'Friends', '0', 'Enchantment', 'Action', '10 ft', NULL, 'S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/friends', NULL, NULL),
(157, 'Gaseous Form', '3', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/gaseous-form', NULL, NULL),
(158, 'Gate', '9', 'Conjuration', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/gate', NULL, NULL),
(159, 'Geas', '5', 'Enchantment', '1 minute', '60 ft', NULL, 'V', '30 days', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/geas', NULL, NULL),
(160, 'Gentle Repose', '2', 'Necromancy', 'Action or Ritual', 'Touch', NULL, 'V,S,M', '10 days', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/gentle-repose', NULL, NULL),
(161, 'Giant Insect', '4', 'Conjuration', 'Action', '60 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/giant-insect', NULL, NULL),
(162, 'Glibness', '8', 'Enchantment', 'Action', 'Self', NULL, 'V', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/glibness', NULL, NULL),
(163, 'Globe of Invulnerability', '6', 'Abjuration', 'Action', 'Self', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/globe-of-invulnerability', NULL, NULL),
(164, 'Glyph of Warding', '3', 'Abjuration', '1 hour', 'Touch', NULL, 'V,S,M', 'Dispelled/Triggered', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/glyph-of-warding', NULL, NULL),
(165, 'Goodberry', '1', 'Conjuration', 'Action', 'Self', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/goodberry', NULL, NULL),
(166, 'Grasping Vine', '4', 'Conjuration', 'Bonus Action', '60 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/grasping-vine', NULL, NULL),
(167, 'Grease', '1', 'Conjuration', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/grease', NULL, NULL),
(168, 'Greater Invisibility', '4', 'Illusion', 'Action', 'Touch', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/greater-invisibility', NULL, NULL),
(169, 'Greater Restoration', '5', 'Abjuration', 'Action', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/greater-restoration', NULL, NULL),
(170, 'Guardian of Faith', '4', 'Conjuration', 'Action', '30 ft', NULL, 'V', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/guardian-of-faith', NULL, NULL),
(171, 'Guards and Wards', '6', 'Abjuration', '1 hour', 'Touch', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/guards-and-wards', NULL, NULL),
(172, 'Guidance', '0', 'Divination', 'Action', 'Touch', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/guidance', NULL, NULL),
(173, 'Guiding Bolt', '1', 'Evocation', 'Action', '120 ft', NULL, 'V,S', '1 round', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/guiding-bolt', NULL, NULL),
(174, 'Gust of Wind', '2', 'Evocation', 'Action', 'Self', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/gust-of-wind', NULL, NULL),
(175, 'Hail of Thorns', '1', 'Conjuration', 'Bonus Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hail-of-thorns', NULL, NULL),
(176, 'Hallow', '5', 'Abjuration', '24 hours', 'Touch', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hallow', NULL, NULL),
(177, 'Hallucinatory Terrain', '4', 'Illusion', '10 minutes', '300 ft', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hallucinatory-terrain', NULL, NULL),
(178, 'Harm', '6', 'Necromancy', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/harm', NULL, NULL),
(179, 'Haste', '3', 'Transmutation', 'Action', '30 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/haste', NULL, NULL),
(180, 'Heal', '6', 'Abjuration', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/heal', NULL, NULL),
(181, 'Healing Word', '1', 'Abjuration', 'Bonus Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/healing-word', NULL, NULL),
(182, 'Heat Metal', '2', 'Transmutation', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/heat-metal', NULL, NULL),
(183, 'Hellish Rebuke', '1', 'Evocation', 'Reaction', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hellish-rebuke', NULL, NULL),
(184, 'Heroes'' Feast', '6', 'Conjuration', '10 minutes', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/heroes--feast', NULL, NULL),
(185, 'Heroism', '1', 'Enchantment', 'Action', 'Touch', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/heroism', NULL, NULL),
(186, 'Hex', '1', 'Enchantment', 'Bonus Action', '90 ft', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hex', NULL, NULL),
(187, 'Hold Monster', '5', 'Enchantment', 'Action', '90 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hold-monster', NULL, NULL),
(188, 'Hold Person', '2', 'Enchantment', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hold-person', NULL, NULL),
(189, 'Holy Aura', '8', 'Abjuration', 'Action', 'Self', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/holy-aura', NULL, NULL),
(190, 'Hunger of Hadar', '3', 'Conjuration', 'Action', '150 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hunger-of-hadar', NULL, NULL),
(191, 'Hunter''s Mark', '1', 'Divination', 'Bonus Action', '90 ft', NULL, 'V', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hunter-s-mark', NULL, NULL),
(192, 'Hypnotic Pattern', '3', 'Illusion', 'Action', '120 ft', NULL, 'S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/hypnotic-pattern', NULL, NULL),
(193, 'Ice Knife', '1', 'Conjuration', 'Action', '60 ft', NULL, 'S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/ice-knife', NULL, NULL),
(194, 'Ice Storm', '4', 'Evocation', 'Action', '300 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/ice-storm', NULL, NULL),
(195, 'Identify', '1', 'Divination', '1 minute or Ritual', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/identify', NULL, NULL),
(196, 'Illusory Script', '1', 'Illusion', '1 minute or Ritual', 'Touch', NULL, 'S,M', '10 days', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/illusory-script', NULL, NULL),
(197, 'Imprisonment', '9', 'Abjuration', '1 minute', '30 ft', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/imprisonment', NULL, NULL),
(198, 'Incendiary Cloud', '8', 'Conjuration', 'Action', '150 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/incendiary-cloud', NULL, NULL),
(199, 'Inflict Wounds', '1', 'Necromancy', 'Action', 'Touch', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/inflict-wounds', NULL, NULL),
(200, 'Insect Plague', '5', 'Conjuration', 'Action', '300 ft', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/insect-plague', NULL, NULL),
(201, 'Invisibility', '2', 'Illusion', 'Action', 'Touch', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/invisibility', NULL, NULL),
(202, 'Jallarzi''s Storm of Radiance', '5', 'Evocation', 'Action', '120 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/jallarzi-s-storm-of-radiance', NULL, NULL),
(203, 'Jump', '1', 'Transmutation', 'Bonus Action', 'Touch', NULL, 'V,S,M', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/jump', NULL, NULL),
(204, 'Knock', '2', 'Transmutation', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/knock', NULL, NULL),
(205, 'Legend Lore', '5', 'Divination', '10 minutes', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/legend-lore', NULL, NULL),
(206, 'Leomund''s Secret Chest', '4', 'Conjuration', 'Action', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/leomund-s-secret-chest', NULL, NULL),
(207, 'Leomund''s Tiny Hut', '3', 'Evocation', '1 minute or Ritual', 'Self', NULL, 'V,S,M', '8 hours', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/leomund-s-tiny-hut', NULL, NULL),
(208, 'Lesser Restoration', '2', 'Abjuration', 'Bonus Action', 'Touch', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/lesser-restoration', NULL, NULL),
(209, 'Levitate', '2', 'Transmutation', 'Action', '60 ft', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/levitate', NULL, NULL),
(210, 'Light', '0', 'Evocation', 'Action', 'Touch', NULL, 'V,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/light', NULL, NULL),
(211, 'Lightning Arrow', '3', 'Transmutation', 'Bonus Action', 'Self', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/lightning-arrow', NULL, NULL),
(212, 'Lightning Bolt', '3', 'Evocation', 'Action', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/lightning-bolt', NULL, NULL),
(213, 'Locate Animals or Plants', '2', 'Divination', 'Action or Ritual', 'Self', NULL, 'V,S,M', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/locate-animals-or-plants', NULL, NULL),
(214, 'Locate Creature', '4', 'Divination', 'Action', 'Self', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/locate-creature', NULL, NULL),
(215, 'Locate Object', '2', 'Divination', 'Action', 'Self', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/locate-object', NULL, NULL),
(216, 'Longstrider', '1', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/longstrider', NULL, NULL),
(217, 'Mage Armor', '1', 'Abjuration', 'Action', 'Touch', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mage-armor', NULL, NULL),
(218, 'Mage Hand', '0', 'Conjuration', 'Action', '30 ft', NULL, 'V,S', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mage-hand', NULL, NULL),
(219, 'Magic Circle', '3', 'Abjuration', '1 minute', '10 ft', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/magic-circle', NULL, NULL),
(220, 'Magic Jar', '6', 'Necromancy', '1 minute', 'Self', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/magic-jar', NULL, NULL),
(221, 'Magic Missile', '1', 'Evocation', 'Action', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/magic-missile', NULL, NULL),
(222, 'Magic Mouth', '2', 'Illusion', '1 minute or Ritual', '30 ft', NULL, 'V,S,M', 'Dispelled', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/magic-mouth', NULL, NULL),
(223, 'Magic Weapon', '2', 'Transmutation', 'Bonus Action', 'Touch', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/magic-weapon', NULL, NULL),
(224, 'Major Image', '3', 'Illusion', 'Action', '120 ft', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/major-image', NULL, NULL),
(225, 'Mass Cure Wounds', '5', 'Abjuration', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mass-cure-wounds', NULL, NULL),
(226, 'Mass Heal', '9', 'Abjuration', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mass-heal', NULL, NULL),
(227, 'Mass Healing Word', '3', 'Abjuration', 'Bonus Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mass-healing-word', NULL, NULL),
(228, 'Mass Suggestion', '6', 'Enchantment', 'Action', '60 ft', NULL, 'V,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mass-suggestion', NULL, NULL),
(229, 'Maze', '8', 'Conjuration', 'Action', '60 ft', NULL, 'V,S', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/maze', NULL, NULL),
(230, 'Meld into Stone', '3', 'Transmutation', 'Action or Ritual', 'Touch', NULL, 'V,S', '8 hours', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/meld-into-stone', NULL, NULL),
(231, 'Melf''s Acid Arrow', '2', 'Evocation', 'Action', '90 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/melf-s-acid-arrow', NULL, NULL),
(232, 'Mending', '0', 'Transmutation', '1 minute', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mending', NULL, NULL),
(233, 'Message', '0', 'Transmutation', 'Action', '120 ft', NULL, 'S,M', '1 round', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/message', NULL, NULL),
(234, 'Meteor Swarm', '9', 'Evocation', 'Action', '1 mile', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/meteor-swarm', NULL, NULL),
(235, 'Mind Blank', '8', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mind-blank', NULL, NULL),
(236, 'Mind Sliver', '0', 'Enchantment', 'Action', '60 ft', NULL, 'V', '1 round', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mind-sliver', NULL, NULL),
(237, 'Mind Spike', '2', 'Divination', 'Action', '120 ft', NULL, 'S', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mind-spike', NULL, NULL),
(238, 'Minor Illusion', '0', 'Illusion', 'Action', '30 ft', NULL, 'S,M', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/minor-illusion', NULL, NULL),
(239, 'Mirage Arcane', '7', 'Illusion', '10 minutes', 'Sight', NULL, 'V,S', '10 days', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mirage-arcane', NULL, NULL),
(240, 'Mirror Image', '2', 'Illusion', 'Action', 'Self', NULL, 'V,S', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mirror-image', NULL, NULL),
(241, 'Mislead', '5', 'Illusion', 'Action', 'Self', NULL, 'S', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mislead', NULL, NULL),
(242, 'Misty Step', '2', 'Conjuration', 'Bonus Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/misty-step', NULL, NULL),
(243, 'Modify Memory', '5', 'Enchantment', 'Action', '30 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/modify-memory', NULL, NULL),
(244, 'Moonbeam', '2', 'Evocation', 'Action', '120 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/moonbeam', NULL, NULL),
(245, 'Mordenkainen''s Faithful Hound', '4', 'Conjuration', 'Action', '30 ft', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mordenkainen-s-faithful-hound', NULL, NULL),
(246, 'Mordenkainen''s Magnificent Mansion', '7', 'Conjuration', '1 minute', '300 ft', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mordenkainen-s-magnificent-mansion', NULL, NULL),
(247, 'Mordenkainen''s Private Sanctum', '4', 'Abjuration', '10 minutes', '120 ft', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mordenkainen-s-private-sanctum', NULL, NULL),
(248, 'Mordenkainen''s Sword', '7', 'Evocation', 'Action', '90 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/mordenkainen-s-sword', NULL, NULL),
(249, 'Move Earth', '6', 'Transmutation', 'Action', '120 ft', NULL, 'V,S,M', '2 hours', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/move-earth', NULL, NULL),
(250, 'Nondetection', '3', 'Abjuration', 'Action', 'Touch', NULL, 'V,S,M', '8 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/nondetection', NULL, NULL),
(251, 'Nystul''s Magic Aura', '2', 'Illusion', 'Action', 'Touch', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/nystul-s-magic-aura', NULL, NULL),
(252, 'Otiluke''s Freezing Sphere', '6', 'Evocation', 'Action', '300 ft', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/otiluke-s-freezing-sphere', NULL, NULL),
(253, 'Otiluke''s Resilient Sphere', '4', 'Evocation', 'Action', '30 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/otiluke-s-resilient-sphere', NULL, NULL),
(254, 'Otto''s Irresistible Dance', '6', 'Enchantment', 'Action', '30 ft', NULL, 'V', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/otto-s-irresistible-dance', NULL, NULL),
(255, 'Pass without Trace', '2', 'Abjuration', 'Action', 'Self', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/pass-without-trace', NULL, NULL),
(256, 'Passwall', '5', 'Transmutation', 'Action', '30 ft', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/passwall', NULL, NULL),
(257, 'Phantasmal Force', '2', 'Illusion', 'Action', '60 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/phantasmal-force', NULL, NULL),
(258, 'Phantasmal Killer', '4', 'Illusion', 'Action', '120 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/phantasmal-killer', NULL, NULL),
(259, 'Phantom Steed', '3', 'Illusion', '1 minute or Ritual', '30 ft', NULL, 'V,S', '1 hour', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/phantom-steed', NULL, NULL),
(260, 'Planar Ally', '6', 'Conjuration', '10 minutes', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/planar-ally', NULL, NULL),
(261, 'Planar Binding', '5', 'Abjuration', '1 hour', '60 ft', NULL, 'V,S,M', '24 hours', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/planar-binding', NULL, NULL),
(262, 'Plane Shift', '7', 'Conjuration', 'Action', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/plane-shift', NULL, NULL),
(263, 'Plant Growth', '3', 'Transmutation', 'Action or 8 hours', '150 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/plant-growth', NULL, NULL),
(264, 'Poison Spray', '0', 'Necromancy', 'Action', '30 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/poison-spray', NULL, NULL),
(265, 'Polymorph', '4', 'Transmutation', 'Action', '60 ft', NULL, 'V,S,M', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/polymorph', NULL, NULL),
(266, 'Power Word Fortify', '7', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/power-word-fortify', NULL, NULL),
(267, 'Power Word Heal', '9', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/power-word-heal', NULL, NULL),
(268, 'Power Word Kill', '9', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/power-word-kill', NULL, NULL),
(269, 'Power Word Stun', '8', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/power-word-stun', NULL, NULL),
(270, 'Prayer of Healing', '2', 'Abjuration', '10 minutes', '30 ft', NULL, 'V', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/prayer-of-healing', NULL, NULL),
(271, 'Prestidigitation', '0', 'Transmutation', 'Action', '10 ft', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/prestidigitation', NULL, NULL),
(272, 'Prismatic Spray', '7', 'Evocation', 'Action', 'Self', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/prismatic-spray', NULL, NULL),
(273, 'Prismatic Wall', '9', 'Abjuration', 'Action', '60 ft', NULL, 'V,S', '10 minutes', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/prismatic-wall', NULL, NULL),
(274, 'Produce Flame', '0', 'Conjuration', 'Bonus Action', 'Self', NULL, 'V,S', '10 minutes', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/produce-flame', NULL, NULL),
(275, 'Programmed Illusion', '6', 'Illusion', 'Action', '120 ft', NULL, 'V,S,M', 'Dispelled', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/programmed-illusion', NULL, NULL),
(276, 'Project Image', '7', 'Illusion', 'Action', '500 miles', NULL, 'V,S,M', '1 day', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/project-image', NULL, NULL),
(277, 'Protection from Energy', '3', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', '1 hour', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/protection-from-energy', NULL, NULL),
(278, 'Protection from Evil and Good', '1', 'Abjuration', 'Action', 'Touch', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/protection-from-evil-and-good', NULL, NULL),
(279, 'Protection from Poison', '2', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/protection-from-poison', NULL, NULL),
(280, 'Purify Food and Drink', '1', 'Transmutation', 'Action or Ritual', '10 ft', NULL, 'V,S', 'Instantaneous', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/purify-food-and-drink', NULL, NULL),
(281, 'Raise Dead', '5', 'Necromancy', '1 hour', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/raise-dead', NULL, NULL),
(282, 'Rary''s Telepathic Bond', '5', 'Divination', 'Action or Ritual', '30 ft', NULL, 'V,S,M', '1 hour', 0, 1, NULL, NULL, NULL, 'https://www.aidedd.org/spell/rary-s-telepathic-bond', NULL, NULL),
(283, 'Ray of Enfeeblement', '2', 'Necromancy', 'Action', '60 ft', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/ray-of-enfeeblement', NULL, NULL),
(284, 'Ray of Frost', '0', 'Evocation', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/ray-of-frost', NULL, NULL),
(285, 'Ray of Sickness', '1', 'Necromancy', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/ray-of-sickness', NULL, NULL),
(286, 'Regenerate', '7', 'Transmutation', '1 minute', 'Touch', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/regenerate', NULL, NULL),
(287, 'Reincarnate', '5', 'Necromancy', '1 hour', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/reincarnate', NULL, NULL),
(288, 'Remove Curse', '3', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/remove-curse', NULL, NULL),
(289, 'Resistance', '0', 'Abjuration', 'Action', 'Touch', NULL, 'V,S', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/resistance', NULL, NULL),
(290, 'Resurrection', '7', 'Necromancy', '1 hour', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/resurrection', NULL, NULL),
(291, 'Reverse Gravity', '7', 'Transmutation', 'Action', '100 ft', NULL, 'V,S,M', '1 minute', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/reverse-gravity', NULL, NULL),
(292, 'Revivify', '3', 'Necromancy', 'Action', 'Touch', NULL, 'V,S,M', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/revivify', NULL, NULL),
(293, 'Rope Trick', '2', 'Transmutation', 'Action', 'Touch', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/rope-trick', NULL, NULL),
(294, 'Sacred Flame', '0', 'Evocation', 'Action', '60 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/sacred-flame', NULL, NULL),
(295, 'Sanctuary', '1', 'Abjuration', 'Bonus Action', '30 ft', NULL, 'V,S,M', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/sanctuary', NULL, NULL),
(296, 'Scorching Ray', '2', 'Evocation', 'Action', '120 ft', NULL, 'V,S', 'Instantaneous', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/scorching-ray', NULL, NULL),
(297, 'Scrying', '5', 'Divination', '10 minutes', 'Self', NULL, 'V,S,M', '10 minutes', 1, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/scrying', NULL, NULL),
(298, 'Searing Smite', '1', 'Evocation', 'Bonus Action', 'Self', NULL, 'V', '1 minute', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/searing-smite', NULL, NULL),
(299, 'See Invisibility', '2', 'Divination', 'Action', 'Self', NULL, 'V,S,M', '1 hour', 0, 0, NULL, NULL, NULL, 'https://www.aidedd.org/spell/see-invisibility', NULL, NULL),
(300, 'Seeming', '5', 'Illusion', 'Action', '30 ft', NULL, 'V, S', '8 hours', 0, 0, '[1,6,7]', NULL, NULL, 'https://www.aidedd.org/spell/seeming', NULL, NULL),
(301, 'Sending', '3', 'Divination', 'Action', 'Unlimited', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[1,2,8]', NULL, NULL, 'https://www.aidedd.org/spell/sending', NULL, NULL),
(302, 'Sequester', '7', 'Transmutation', 'Action', 'Touch', NULL, 'V, S, M', 'Dispelled', 0, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/sequester', NULL, NULL),
(303, 'Shapechange', '9', 'Transmutation', 'Action', 'Self', NULL, 'V, S, M', '1 hour', 1, 0, '[3,8]', NULL, NULL, 'https://www.aidedd.org/spell/shapechange', NULL, NULL),
(304, 'Shatter', '2', 'Evocation', 'Action', '60 ft', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[1,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/shatter', NULL, NULL),
(305, 'Shield', '1', 'Abjuration', 'Reaction', 'Self', NULL, 'V, S', '1 round', 0, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/shield', NULL, NULL),
(306, 'Shield of Faith', '1', 'Abjuration', 'Bonus Action', '60 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[2,4]', NULL, NULL, 'https://www.aidedd.org/spell/shield-of-faith', NULL, NULL),
(307, 'Shillelagh', '0', 'Transmutation', 'Bonus Action', 'Self', NULL, 'V, S, M', '1 minute', 0, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/shillelagh', NULL, NULL),
(308, 'Shining Smite', '2', 'Transmutation', 'Bonus Action', 'Self', NULL, 'V', '1 minute', 1, 0, '[4]', NULL, NULL, 'https://www.aidedd.org/spell/shining-smite', NULL, NULL),
(309, 'Shocking Grasp', '0', 'Evocation', 'Action', 'Touch', NULL, 'V, S', 'Instantaneous', 0, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/shocking-grasp', NULL, NULL),
(310, 'Silence', '2', 'Illusion', 'Action or Ritual', '120 ft', NULL, 'V, S', '10 minutes', 1, 1, '[1,2,5]', NULL, NULL, 'https://www.aidedd.org/spell/silence', NULL, NULL),
(311, 'Silent Image', '1', 'Illusion', 'Action', '60 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/silent-image', NULL, NULL),
(312, 'Simulacrum', '7', 'Illusion', '12 hours', 'Touch', NULL, 'V, S, M', 'Dispelled', 0, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/simulacrum', NULL, NULL),
(313, 'Sleep', '1', 'Enchantment', 'Action', '60 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/sleep', NULL, NULL),
(314, 'Sleet Storm', '3', 'Conjuration', 'Action', '150 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[3,6]', NULL, NULL, 'https://www.aidedd.org/spell/sleet-storm', NULL, NULL),
(315, 'Slow', '3', 'Transmutation', 'Action', '120 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/slow', NULL, NULL),
(316, 'Sorcerous Burst', '0', 'Evocation', 'Action', '120 ft', NULL, 'V, S', 'Instantaneous', 0, 0, '[6]', NULL, NULL, 'https://www.aidedd.org/spell/sorcerous-burst', NULL, NULL),
(317, 'Spare the Dying', '0', 'Necromancy', 'Action', '15 ft', NULL, 'V, S', 'Instantaneous', 0, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/spare-the-dying', NULL, NULL),
(318, 'Speak with Animals', '1', 'Divination', 'Action or Ritual', 'Self', NULL, 'V, S', '10 minutes', 0, 1, '[1,3,5]', NULL, NULL, 'https://www.aidedd.org/spell/speak-with-animals', NULL, NULL),
(319, 'Speak with Dead', '3', 'Necromancy', 'Action', '10 ft', NULL, 'V, S, M', '10 minutes', 0, 0, '[1,2]', NULL, NULL, 'https://www.aidedd.org/spell/speak-with-dead', NULL, NULL),
(320, 'Speak with Plants', '3', 'Transmutation', 'Action', 'Self', NULL, 'V, S', '10 minutes', 0, 0, '[1,3,5]', NULL, NULL, 'https://www.aidedd.org/spell/speak-with-plants', NULL, NULL),
(321, 'Spider Climb', '2', 'Transmutation', 'Action', 'Touch', NULL, 'V, S, M', '1 hour', 1, 0, '[6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/spider-climb', NULL, NULL),
(322, 'Spike Growth', '2', 'Transmutation', 'Action', '150 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[3,5]', NULL, NULL, 'https://www.aidedd.org/spell/spike-growth', NULL, NULL),
(323, 'Spirit Guardians', '3', 'Conjuration', 'Action', 'Self', NULL, 'V, S, M', '10 minutes', 1, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/spirit-guardians', NULL, NULL),
(324, 'Spiritual Weapon', '2', 'Evocation', 'Bonus Action', '60 ft', NULL, 'V, S', '1 minute', 1, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/spiritual-weapon', NULL, NULL),
(325, 'Staggering Smite', '4', 'Enchantment', 'Bonus Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, '[4]', NULL, NULL, 'https://www.aidedd.org/spell/staggering-smite', NULL, NULL),
(326, 'Starry Wisp', '0', 'Evocation', 'Action', '60 ft', NULL, 'V, S', 'Instantaneous', 0, 0, '[1,3]', NULL, NULL, 'https://www.aidedd.org/spell/starry-wisp', NULL, NULL),
(327, 'Steel Wind Strike', '5', 'Conjuration', 'Action', '30 ft', NULL, 'S, M', 'Instantaneous', 0, 0, '[5,8]', NULL, NULL, 'https://www.aidedd.org/spell/steel-wind-strike', NULL, NULL),
(328, 'Stinking Cloud', '3', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/stinking-cloud', NULL, NULL),
(329, 'Stone Shape', '4', 'Transmutation', 'Action', 'Touch', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[2,3,8]', NULL, NULL, 'https://www.aidedd.org/spell/stone-shape', NULL, NULL),
(330, 'Stoneskin', '4', 'Transmutation', 'Action', 'Touch', NULL, 'V, S, M', '1 hour', 1, 0, '[3,5,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/stoneskin', NULL, NULL),
(331, 'Storm of Vengeance', '9', 'Conjuration', 'Action', '1 mile', NULL, 'V, S', '1 minute', 1, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/storm-of-vengeance', NULL, NULL),
(332, 'Suggestion', '2', 'Enchantment', 'Action', '30 ft', NULL, 'V, M', '8 hours', 1, 0, '[1,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/suggestion', NULL, NULL),
(333, 'Summon Aberration', '4', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[7,8]', NULL, NULL, 'https://www.aidedd.org/spell/summon-aberration', NULL, NULL),
(334, 'Summon Beast', '2', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[3,5]', NULL, NULL, 'https://www.aidedd.org/spell/summon-beast', NULL, NULL),
(335, 'Summon Celestial', '5', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[2,4]', NULL, NULL, 'https://www.aidedd.org/spell/summon-celestial', NULL, NULL),
(336, 'Summon Construct', '4', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/summon-construct', NULL, NULL),
(337, 'Summon Dragon', '5', 'Conjuration', 'Action', '60 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[3,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/summon-dragon', NULL, NULL),
(338, 'Summon Elemental', '4', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[3,5,8]', NULL, NULL, 'https://www.aidedd.org/spell/summon-elemental', NULL, NULL),
(339, 'Summon Fey', '3', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[3,5,7]', NULL, NULL, 'https://www.aidedd.org/spell/summon-fey', NULL, NULL),
(340, 'Summon Fiend', '6', 'Conjuration', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[7,8]', NULL, NULL, 'https://www.aidedd.org/spell/summon-fiend', NULL, NULL),
(341, 'Summon Undead', '3', 'Necromancy', 'Action', '90 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[7,8]', NULL, NULL, 'https://www.aidedd.org/spell/summon-undead', NULL, NULL),
(342, 'Sunbeam', '6', 'Evocation', 'Action', 'Self', NULL, 'V, S, M', '1 minute', 1, 0, '[3,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/sunbeam', NULL, NULL),
(343, 'Sunburst', '8', 'Evocation', 'Action', '150 ft', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[3,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/sunburst', NULL, NULL),
(344, 'Swift Quiver', '5', 'Transmutation', 'Bonus Action', 'Self', NULL, 'V, S, M', '1 minute', 1, 0, '[5]', NULL, NULL, 'https://www.aidedd.org/spell/swift-quiver', NULL, NULL),
(345, 'Symbol', '7', 'Abjuration', '1 minute', 'Touch', NULL, 'V, S, M', 'Dispelled/Triggered', 0, 0, '[1,2,8]', NULL, NULL, 'https://www.aidedd.org/spell/symbol', NULL, NULL),
(346, 'Synaptic Static', '5', 'Enchantment', 'Action', '120 ft', NULL, 'V, S', 'Instantaneous', 0, 0, '[1,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/synaptic-static', NULL, NULL),
(347, 'Tasha''s Bubbling Cauldron', '6', 'Conjuration', 'Action', '5 ft', NULL, 'V, S, M', '10 minutes', 0, 0, '[3,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/tasha-s-bubbling-cauldron', NULL, NULL),
(348, 'Tasha''s Hideous Laughter', '1', 'Enchantment', 'Action', '30 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[1,8]', NULL, NULL, 'https://www.aidedd.org/spell/tasha-s-hideous-laughter', NULL, NULL),
(349, 'Telekinesis', '5', 'Transmutation', 'Action', '60 ft', NULL, 'V, S', '10 minutes', 1, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/telekinesis', NULL, NULL),
(350, 'Telepathy', '8', 'Divination', 'Action', 'Unlimited', NULL, 'V, S, M', '24 hours', 0, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/telepathy', NULL, NULL),
(351, 'Teleport', '7', 'Conjuration', 'Action', '10 ft', NULL, 'V', 'Instantaneous', 0, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/teleport', NULL, NULL),
(352, 'Teleportation Circle', '5', 'Conjuration', '1 minute', '10 ft', NULL, 'V, M', '1 round', 0, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/teleportation-circle', NULL, NULL),
(353, 'Tenser''s Floating Disk', '1', 'Conjuration', 'Action or Ritual', '30 ft', NULL, 'V, S, M', '1 hour', 0, 1, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/tenser-s-floating-disk', NULL, NULL),
(354, 'Thaumaturgy', '0', 'Transmutation', 'Action', '30 ft', NULL, 'V', '1 minute', 0, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/thaumaturgy', NULL, NULL),
(355, 'Thorn Whip', '0', 'Transmutation', 'Action', '30 ft', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/thorn-whip', NULL, NULL),
(356, 'Thunderclap', '0', 'Evocation', 'Action', 'Self', NULL, 'S', 'Instantaneous', 0, 0, '[1,3,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/thunderclap', NULL, NULL),
(357, 'Thunderous Smite', '1', 'Evocation', 'Bonus Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, '[4]', NULL, NULL, 'https://www.aidedd.org/spell/thunderous-smite', NULL, NULL),
(358, 'Thunderwave', '1', 'Evocation', 'Action', 'Self', NULL, 'V, S', 'Instantaneous', 0, 0, '[1,3,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/thunderwave', NULL, NULL),
(359, 'Time Stop', '9', 'Transmutation', 'Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/time-stop', NULL, NULL),
(360, 'Toll the Dead', '0', 'Necromancy', 'Action', '60 ft', NULL, 'V, S', 'Instantaneous', 0, 0, '[2,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/toll-the-dead', NULL, NULL),
(361, 'Tongues', '3', 'Divination', 'Action', 'Touch', NULL, 'V, M', '1 hour', 0, 0, '[1,2,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/tongues', NULL, NULL),
(362, 'Transport via Plants', '6', 'Conjuration', 'Action', '10 ft', NULL, 'V, S', '1 minute', 0, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/transport-via-plants', NULL, NULL),
(363, 'Tree Stride', '5', 'Conjuration', 'Action', 'Self', NULL, 'V, S', '1 minute', 1, 0, '[3,5]', NULL, NULL, 'https://www.aidedd.org/spell/tree-stride', NULL, NULL),
(364, 'True Polymorph', '9', 'Transmutation', 'Action', '30 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/true-polymorph', NULL, NULL),
(365, 'True Resurrection', '9', 'Necromancy', '1 hour', 'Touch', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[2,3]', NULL, NULL, 'https://www.aidedd.org/spell/true-resurrection', NULL, NULL),
(366, 'True Seeing', '6', 'Divination', 'Action', 'Touch', NULL, 'V, S, M', '1 hour', 0, 0, '[1,2,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/true-seeing', NULL, NULL),
(367, 'True Strike', '0', 'Divination', 'Action', 'Self', NULL, 'S, M', 'Instantaneous', 0, 0, '[1,6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/true-strike', NULL, NULL),
(368, 'Tsunami', '8', 'Conjuration', '1 minute', '1 mile', NULL, 'V, S', '6 rounds', 1, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/tsunami', NULL, NULL),
(369, 'Unseen Servant', '1', 'Conjuration', 'Action or Ritual', '60 ft', NULL, 'V, S, M', '1 hour', 0, 1, '[1,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/unseen-servant', NULL, NULL),
(370, 'Vampiric Touch', '3', 'Necromancy', 'Action', 'Self', NULL, 'V, S', '1 minute', 1, 0, '[6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/vampiric-touch', NULL, NULL),
(371, 'Vicious Mockery', '0', 'Enchantment', 'Action', '60 ft', NULL, 'V', 'Instantaneous', 0, 0, '[1]', NULL, NULL, 'https://www.aidedd.org/spell/vicious-mockery', NULL, NULL),
(372, 'Vitriolic Sphere', '4', 'Evocation', 'Action', '150 ft', NULL, 'V, S, M', 'Instantaneous', 0, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/vitriolic-sphere', NULL, NULL),
(373, 'Wall of Fire', '4', 'Evocation', 'Action', '120 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[3,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/wall-of-fire', NULL, NULL),
(374, 'Wall of Force', '5', 'Evocation', 'Action', '120 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/wall-of-force', NULL, NULL),
(375, 'Wall of Ice', '6', 'Evocation', 'Action', '120 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/wall-of-ice', NULL, NULL),
(376, 'Wall of Stone', '5', 'Evocation', 'Action', '120 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[3,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/wall-of-stone', NULL, NULL),
(377, 'Wall of Thorns', '6', 'Conjuration', 'Action', '120 ft', NULL, 'V, S, M', '10 minutes', 1, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/wall-of-thorns', NULL, NULL),
(378, 'Warding Bond', '2', 'Abjuration', 'Action', 'Touch', NULL, 'V, S, M', '1 hour', 0, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/warding-bond', NULL, NULL),
(379, 'Water Breathing', '3', 'Transmutation', 'Action or Ritual', '30 ft', NULL, 'V, S, M', '24 hours', 0, 1, '[3,5,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/water-breathing', NULL, NULL),
(380, 'Water Walk', '3', 'Transmutation', 'Action or Ritual', '30 ft', NULL, 'V, S, M', '1 hour', 0, 1, '[2,3,5,6]', NULL, NULL, 'https://www.aidedd.org/spell/water-walk', NULL, NULL),
(381, 'Web', '2', 'Conjuration', 'Action', '60 ft', NULL, 'V, S, M', '1 hour', 1, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/web', NULL, NULL),
(382, 'Weird', '9', 'Illusion', 'Action', '120 ft', NULL, 'V, S', '1 minute', 1, 0, '[8]', NULL, NULL, 'https://www.aidedd.org/spell/weird', NULL, NULL),
(383, 'Wind Walk', '6', 'Transmutation', '1 minute', '30 ft', NULL, 'V, S, M', '8 hours', 0, 0, '[3]', NULL, NULL, 'https://www.aidedd.org/spell/wind-walk', NULL, NULL),
(384, 'Wind Wall', '3', 'Evocation', 'Action', '120 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[3,5]', NULL, NULL, 'https://www.aidedd.org/spell/wind-wall', NULL, NULL),
(385, 'Wish', '9', 'Conjuration', 'Action', 'Self', NULL, 'V', 'Instantaneous', 0, 0, '[6,8]', NULL, NULL, 'https://www.aidedd.org/spell/wish', NULL, NULL),
(386, 'Witch Bolt', '1', 'Evocation', 'Action', '60 ft', NULL, 'V, S, M', '1 minute', 1, 0, '[6,7,8]', NULL, NULL, 'https://www.aidedd.org/spell/witch-bolt', NULL, NULL),
(387, 'Word of Radiance', '0', 'Evocation', 'Action', 'Self', NULL, 'V, M', 'Instantaneous', 0, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/word-of-radiance', NULL, NULL),
(388, 'Word of Recall', '6', 'Conjuration', 'Action', '5 ft', NULL, 'V', 'Instantaneous', 0, 0, '[2]', NULL, NULL, 'https://www.aidedd.org/spell/word-of-recall', NULL, NULL),
(389, 'Wrathful Smite', '1', 'Necromancy', 'Bonus Action', 'Self', NULL, 'V', '1 minute', 0, 0, '[4]', NULL, NULL, 'https://www.aidedd.org/spell/wrathful-smite', NULL, NULL),
(390, 'Yolande''s Regal Presence', '5', 'Enchantment', 'Action', 'Self', NULL, 'V, S, M', '1 minute', 1, 0, '[1,6,8]', NULL, NULL, 'https://www.aidedd.org/spell/yolande-s-regal-presence', NULL, NULL),
(391, 'Zone of Truth', '2', 'Enchantment', 'Action', '60 ft', NULL, 'V, S', '10 minutes', 0, 0, '[1,2,4]', NULL, NULL, 'https://www.aidedd.org/spell/zone-of-truth', NULL, NULL);